apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-01
  namespace: nginx-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nginx-1.${DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-1-service
            port:
              number: 80